//! Concrete shadcn/ui-style components, each a plain [`egui::Widget`].
//!
//! Each component lives in its own module. The primary type is re-exported at
//! the crate root; variant/size enums stay module-qualified (e.g.
//! [`button::Variant`] vs [`badge::Variant`]) to avoid name clashes.

pub mod accordion;
pub mod alert;
pub mod alert_dialog;
pub mod aspect_ratio;
pub mod attachment;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod bubble;
pub mod button;
pub mod button_group;
pub mod calendar;
pub mod card;
pub mod carousel;
pub mod chart;
pub mod checkbox;
pub mod collapsible;
pub mod combobox;
pub mod command;
pub mod context_menu;
pub mod data_table;
pub mod date_picker;
pub mod dialog;
pub mod drawer;
pub mod dropdown_menu;
pub mod empty;
pub mod field;
pub mod grid;
pub mod hover_card;
pub mod icon;
pub mod input;
pub mod input_group;
pub mod input_otp;
pub mod item;
pub mod kbd;
pub mod label;
pub mod marker;
pub mod menubar;
pub mod message;
pub mod message_scroller;
pub mod native_select;
pub mod navigation_menu;
pub mod pagination;
pub mod popover;
pub mod progress;
pub mod radio_group;
pub mod resizable;
pub mod scroll_area;
pub mod select;
pub mod separator;
pub mod sheet;
pub mod sidebar;
pub mod sidebar_menu;
pub mod skeleton;
pub mod slider;
pub mod sonner;
pub mod spinner;
pub mod switch;
pub mod table;
pub mod tabs;
pub mod textarea;
pub mod time_picker;
pub mod toggle;
pub mod toggle_group;
pub mod tooltip;
pub mod typography;

pub use accordion::{Accordion, AccordionMetrics};
pub use alert::{Alert, AlertMetrics};
pub use alert_dialog::AlertDialog;
pub use aspect_ratio::AspectRatio;
pub use attachment::{Attachment, AttachmentMetrics};
pub use avatar::Avatar;
pub use badge::{Badge, BadgeMetrics, BadgeStyle};
pub use breadcrumb::{Breadcrumb, BreadcrumbMetrics};
pub use bubble::{Bubble, BubbleGroup, BubbleStyle as BubbleSurfaceStyle};
pub use button::{Button, ButtonStyle};
pub use button_group::{ButtonGroup, ButtonGroupMetrics};
pub use calendar::{Calendar, CalendarMetrics, Date};
pub use card::Card;
pub use carousel::Carousel;
pub use chart::Chart;
pub use checkbox::{Checkbox, CheckboxMetrics};
pub use collapsible::{Collapsible, CollapsibleMetrics};
pub use combobox::Combobox;
pub use command::{Command, CommandGroup, CommandItem};
pub use context_menu::ContextMenu;
pub use data_table::{DataColumn, DataTable, DataTableMetrics};
pub use date_picker::DatePicker;
pub use dialog::Dialog;
pub use drawer::Drawer;
pub use dropdown_menu::DropdownMenu;
pub use empty::Empty;
pub use field::Field;
pub use grid::Grid;
pub use hover_card::HoverCard;
pub use icon::Icon;
pub use input::{Input, InputMetrics};
pub use input_group::{InputGroup, InputGroupMetrics};
pub use input_otp::{InputOtp, OtpMode};
pub use item::Item;
pub use kbd::Kbd;
pub use label::Label;
pub use marker::{Marker, MarkerStyle};
pub use menubar::{Menubar, MenubarMenu};
pub use message::{BubbleStyle, Message, MessageGroup, MessageResponse};
pub use message_scroller::MessageScroller;
pub use native_select::NativeSelect;
pub use navigation_menu::{NavItem, NavResponse, NavigationMenu};
pub use pagination::Pagination;
pub use popover::Popover;
pub use progress::Progress;
pub use radio_group::{RadioGroup, RadioGroupMetrics};
pub use resizable::{Resizable, ResizableMetrics};
pub use scroll_area::ScrollArea;
pub use select::Select;
pub use separator::Separator;
pub use sheet::Sheet;
pub use sidebar::{Sidebar, SidebarTrigger};
pub use sidebar_menu::SidebarMenu;
pub use skeleton::Skeleton;
pub use slider::{Slider, SliderMetrics};
pub use sonner::{Toast, Toaster};
pub use spinner::{Spinner, SpinnerMetrics, SpinnerStyle};
pub use switch::{Switch, SwitchMetrics};
pub use table::{Sizing, Table, TableMetrics};
pub use tabs::{Tabs, TabsResponse};
pub use textarea::Textarea;
pub use time_picker::{Time, TimePicker};
pub use toggle::Toggle;
pub use toggle_group::ToggleGroup;
pub use tooltip::Tooltip;
pub use typography::Typography;
